### ISSUE TITLE
Back button broken

### ISSUE THREAD

**Issue by rad182** [LoganWright/SimpleCam#23]
Hi, when I tap back button in the preview photo it just shows black. Any solution?

**Comment by LoganWright** [comment]
Hi @rad182 

Not sure off of the top of my head, this project hasn't been updated in a while, and w/ iOS 9, there could be multiple problems.  Can you look into the class and see if button events are being received?

This is on my list of things to do, but I just haven't had time recently.  I'm sorry I can't be more helpful, but I don't have a good timeline of when I'll get to this.

Best,

Logan

**Comment by rad182** [comment]
@LoganWright yes the back button method is being called but it's still showing black screen. Probably some ios 9 issue. It's okay I'll send a pull request if I find a solution

**Comment by rad182** [comment]
https://github.com/LoganWright/SimpleCam/pull/24
